export const images = {
  logo: {
    naver: '/src/assets/images/logo-naver.png',
  },
  login: {
    background: '/src/assets/images/login-background.png',
  },
  waitingRoom: {
    background: '/src/assets/images/wating-room-bg.png',
    copy: '/src/assets/images/ic-copy.png',
    mail: '/src/assets/images/ic-mail.png',
    exit: '/src/assets/images/ic-exit.png',
    crown: '/src/assets/images/ic-crown.png',
    emit: '/src/assets/images/ic-emit.png',
    info: '/src/assets/images/icon_info.png',
    closeWhite: '/src/assets/images/ic-close-white.png',
    cancelButton: '/src/assets/images/cancel-button.png',
    readyButton: '/src/assets/images/ready-button.png',
  },
  gameRoom: {
    background: '/src/assets/images/game-room-background.png',
  },
  dummy: {
    dummy1: '/src/assets/images/dummy1.png',
    dummy2: '/src/assets/images/dummy2.png',
    dummy3: '/src/assets/images/dummy3.png',
  },
  icon: {
    volume_on: '/src/assets/images/icon-volume-on.png',
    volume_off: '/src/assets/images/icon-volume-off.png',
    shop: '/src/assets/images/icon-shop.png',
    setting: '/src/assets/images/icon-setting.png',
    point: '/src/assets/images/icon-point.png',
    friend: '/src/assets/images/icon-friend.png',
    left: '/src/assets/images/icon-left.png',
    right: '/src/assets/images/icon-right.png',
    refresh: '/src/assets/images/icon-refresh.png',
    invite: '/src/assets/images/icon-invite.png',
    plus: '/src/assets/images/icon-plus.png',
    room: '/src/assets/images/icon-room.png',
    people: '/src/assets/images/icon-people.png',
    success: '/src/assets/images/icon-success.png',
    error: '/src/assets/images/icon-error.png',
    info: '/src/assets/images/icon-info.png',
    warning: '/src/assets/images/icon-warning.png',
    close: '/src/assets/images/icon-close-black.png',
  },
  button: {
    close: '/src/assets/images/btn-close.png',
    create: '/src/assets/images/btn-create.png',
    checked: '/src/assets/images/btn-checked.png',
    unchecked: '/src/assets/images/btn-unchecked.png',
    bought: '/src/assets/images/btn-bg-already-buy.png',
    buy: '/src/assets/images/btn-bg-buy.png',
  },
  lobby: {
    background: '/src/assets/images/lobby-background.png',
  },
  store: {
    background: '/src/assets/images/store-background.png',
    owner: '/src/assets/images/character-store-owner.png',
    bubble: '/src/assets/images/img-speech-bubble.png',
    buygra: '/src/assets/images/img-character-buy-effect.png',
    boughtgra: '/src/assets/images/img-character-already-buy-effect.png',
    dog1: '/src/assets/images/character-dog.png',
    dog2: '/src/assets/images/character-dog2.png',
    rabbit: '/src/assets/images/character-rabbit.png',
    hedgehog: '/src/assets/images/character-hedgehog.png',
    panda: '/src/assets/images/character-panda.png',
    whale: '/src/assets/images/character-whale.png',
    phoenix: '/src/assets/images/character-phoenix.png',
    squirrel: '/src/assets/images/character-squirrel.png',
    unicorn: '/src/assets/images/character-unicorn.png',
  },
  default: {
    character: '/src/assets/images/default-character.png',
  },
  map: {
    start: '/src/assets/images/map/시작점.png',
    vietnam: '/src/assets/images/map/베트남.png',
    revenue: '/src/assets/images/map/세금징수.png',
    thailand: '/src/assets/images/map/태국.png',
    goldKey1: '/src/assets/images/map/황금열쇠1.png',
    singapore: '/src/assets/images/map/싱가포르.png',
    egypt: '/src/assets/images/map/이집트.png',
    southAfrica: '/src/assets/images/map/남아공.png',
    transactionSuspended: '/src/assets/images/map/거래정지.png',
  },
};
