export const images = {
  logo: {
    naver: '/src/assets/images/logo-naver.png',
  },
  login: {
    background: '/src/assets/images/login-background.png',
  },
  waitingRoom: {
    background: '/src/assets/images/wating-room-bg.png',
    copy: '/src/assets/images/ic-copy.png',
    mail: '/src/assets/images/ic-mail.png',
    exit: '/src/assets/images/ic-exit.png',
    crown: '/src/assets/images/ic-crown.png',
    emit: '/src/assets/images/ic-emit.png',
    info: '/src/assets/images/icon_info.png',
    closeWhite: '/src/assets/images/ic-close-white.png',
    cancelButton: '/src/assets/images/cancel-button.png',
    readyButton: '/src/assets/images/ready-button.png',
  },
  dummy: {
    dummy1: '/src/assets/images/dummy1.png',
    dummy2: '/src/assets/images/dummy2.png',
    dummy3: '/src/assets/images/dummy3.png',
    dummyCharacter1: '/src/assets/images/dummyCharacter1.png',
    dummyCharacter2: '/src/assets/images/dummyCharacter2.png',
    dummyCharacter3: '/src/assets/images/dummyCharacter3.png',
    dummyCharacter4: '/src/assets/images/dummyCharacter4.png',
  },
  icon: {
    volume_on: '/src/assets/images/icon-volume-on.png',
    volume_off: '/src/assets/images/icon-volume-off.png',
    shop: '/src/assets/images/icon-shop.png',
    setting: '/src/assets/images/icon-setting.png',
    point: '/src/assets/images/icon-point.png',
    friend: '/src/assets/images/icon-friend.png',
    left: '/src/assets/images/icon-left.png',
    right: '/src/assets/images/icon-right.png',
    refresh: '/src/assets/images/icon-refresh.png',
    invite: '/src/assets/images/icon-invite.png',
    plus: '/src/assets/images/icon-plus.png',
    room: '/src/assets/images/icon-room.png',
    people: '/src/assets/images/icon-people.png',
  },
  button: {
    close: '/src/assets/images/btn-close.png',
    create: '/src/assets/images/btn-create.png',
    checked: '/src/assets/images/btn-checked.png',
    unchecked: '/src/assets/images/btn-unchecked.png',
  },
  lobby: {
    background: '/src/assets/images/lobby-background.png',
  },
  default: {
    character: '/src/assets/images/default-character.png',
  },
  mypage: {
    lock: '/src/assets/images/ic-lock.png',
    choice: '/src/assets/images/ic-choice.png',
  },
};
