# Generated by Django 3.2.18 on 2023-09-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('game_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('asset', models.IntegerField(blank=True, null=True)),
                ('land_amount', models.IntegerField(blank=True, null=True)),
                ('stock_amount', models.IntegerField(blank=True, null=True)),
                ('stock_asset', models.IntegerField(blank=True, null=True)),
                ('loan_num', models.IntegerField(blank=True, null=True)),
                ('door_used_num', models.IntegerField(blank=True, null=True)),
                ('key_used_num', models.IntegerField(blank=True, null=True)),
                ('angel_used_num', models.IntegerField(blank=True, null=True)),
                ('survival_turn', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_result',
                'managed': False,
            },
        ),
    ]
